python run.py \
--model "scheduled-sampling" \
--name "ss_samplek" \
--dataset "OpenSubtitles" \
--dataid "../cotk_data/iwslt14" \
--wvid "../cotk_data/glove.6B.300d.txt" \
--lr 0.0001 \
--eh_size 175 \
--dh_size 175 \
--droprate 0.2 \
--device ${1:-0} \
--decode_mode "sample" \
--epoch 20 \
--seed 2 \
--batch_per_epoch 500