python run.py ^
--model "scheduled-sampling" ^
--dataset "OpenSubtitles" ^
--dataid "D:/Documents/THU/Cotk/data/iwslt14" ^
--wvid "D:/.cotk_cache/glove/glove.6B.300d.txt" ^
--lr 0.0005 ^
--eh_size 175 ^
--dh_size 175 ^
--droprate 0.2 ^
--decode_mode "samplek" ^
--epoch 10