python run.py \
--name "basic_max_10" \
--model "basic" \
--dataset "OpenSubtitles" \
--dataid "../cotk_data/iwslt14" \
--wvid "../cotk_data/glove.6B.300d.txt" \
--lr 0.0001 \
--eh_size 175 \
--dh_size 175 \
--droprate 0.2 \
--device ${1:-0} \
--epoch 10 \
--decode_mode "max"